function allCards(){
    return [
        // Lesson 1
        {front:"Das Buch", back:"Le livre"},
        {front:"Das Loch", back:"Le trou"},
        {front:"Die Nacht", back:"La nuit"},
        {front:"Das Wiedervereinigung", back:"La réunification"},
        {front:"Ich spreche Deutsch", back:"Je parle allemand"},
        {front:"Das Geschäft", back:"Le magasin"},
        {front:"Zurückkommen", back:"Revenir"},
        // Lesson 2
        {front:"Ich spreche nicht gut Deutsch", back:"Je ne parle pas bien allemand"},
        {front:"Ich spreche ein bisschen Deutsch", back:"Je parle un peu allemand"},
        {front:"Ich verstehe ziemlich gut, aber es fällt mich schwer zu sprechen", back:"Je comprends assez bien mais j'ai du mal à parler"},
        {front:"Ich hatte Deutsch in der Schule", back:"J'ai étudié l'allemand à l'école"},
        {front:"Wie bitte?", back:"Comment? Pardon?"},
        {front:"Es tut mir leid, aber ich verstehe das nicht", back:"Désolé, mais je ne comprends pas"},
        {front:"Kannst du das wiederholen?", back:"Peux-tu répéter?"},
        {front:"Könntest du lauter sprechen?", back:"Pourrais-tu parler plus fort?"},
        {front:"Langsamer, bitte", back:"Plus lentement s'il te plaît"},
        {front:"Kannst du das buchstabieren?", back:"Peux-tu l'épeler?"},
        {front:"Wie shreibt man das?", back:"Comment ca s'écrit?"},
        {front:"Ich verstehe das nicht", back:"Je ne comprends pas"},
        {front:"Ich verstehe nichts", back:"Je ne comprends rien"},
        {front:"Ich habe nichts verstanden", back:"Je n'ai rien compris"},
        {front:"Wie nennt man das?", back:"Comment appelle-t-on ca?"},
        {front:"Wie sagt man ... auf Deutch?", back:"Comment dit on ... en allemand?"},
        {front:"Was bedeutet ...?", back:"Qu'est ce que ... veut dire?"},
        {front:"Wie spricht man ... aus?", back:"Comment se prononce ... ?"},
        // Lesson 3
        {front:"Der Sozialismus", back:"Le socialisme"},
        {front:"Der Sozialist", back:"Le socialist"},
        {front:"Die Sozialistin", back:"La socialiste"},
        {front:"Der Verkäufer", back:"Le vendeur"},
        {front:"Die Verkäuferin", back:"La vendeuse"},
        {front:"Die Toleranz", back:"La tolérance"},
        {front:"Die Revolution", back:"La révolution"},
        {front:"Das Fenster", back:"La fenêtre"},
        {front:"Der Junge", back:"Le garcon"},
        {front:"Die Schwester", back:"La soeur"},
        {front:"Der Sänger", back:"Le chanteur"},
        {front:"Die Sängerin", back:"La chanteuse"},
        {front:"Der Pazifist", back:"Le pacifiste"},
        {front:"Die Pazifistin", back:"La pacifiste"},
        {front:"Der Student", back:"L'étudiant"},
        {front:"Die Studentin", back:"L'étudiante"},
        {front:"Der Kollege", back:"Die Kollegin"},
        {front:"Das Brötchen", back:"Le petit pain"},
        {front:"Das Konto", back:"Le compte"},
        {front:"Das Argument", back:"L'argument"},
        {front:"Das Geschenk", back:"Le cadeau"},
        // Lesson 4
        {front:"Könnten Sie mir helfen?", back:"Pourriez-vous m'aider?"},
        {front:"Könnten Sie ...?", back:"Pourriez-vous ...?"},
        {front:"Kann ich ...?", back:"Puis-je ...?"},
        {front:"Haben Sie ...?", back:"Avez-vous ...?"},
        {front:"Gibt es ...?", back:"Y a-t-il ...?"},
        {front:"Wo gibt es ...?", back:"Ou y a-t-il ...?"},
        {front:"Ich suche nach ...?", back:"Je cherche ..."},
        {front:"Ich möchte ...", back:"Je voudrais ..."},
        {front:"Ich brauche ...", back:"J'ai besoin de ..."},
        {front:"Vielen Dank", back:"Merci beaucoup"},
        {front:"Danke für Ihre Hilfe", back:"Merci pour votre aide"},
        {front:"Ich bin Ihnen für ... sehr dankbar", back:"Je vous suis très reconnaissant pour ..."},
        {front:"Nichts zu danken", back:"De rien"},
        {front:"Gern geschehen", back:"Il n'y a pas de quoi"},
        {front:"Entschuldigung!", back:"Excusez-moi!"},
        {front:"Verzeihung!", back:"Pardon!"},
        {front:"Es tut mir wirklich leid", back:"Je suis vraiment désolé"},
        {front:"Es tut mir leid, dass ich zu spät bin", back:"Je suis désolé d'être en retard"},
        {front:"Das ist nicht schlimm", back:"Ce n'est pas grave"},
        // Lesson 5
        {front:"Das Büro", back:"Le bureau"},
        {front:"Das Kind", back:"L'enfant"},
        {front:"Die Zeitung", back:"Le journal"},
        {front:"Die Möglichkeit", back:"La possibilité"},
        {front:"Der Kuss", back:"Le baiser"},
        {front:"Der Traum", back:"Le rêve"},
        {front:"Der Bus", back:"Le bus"},
        {front:"Das Schloss", back:"La serrure"},

    ]
}