function allMeals(){
    return [
        {name:"Spaghetti bolognese"},
        {name:"Guacamole"},
        {name:"Pumpkin soup"},
        {name:"Pea soup"},
        {name:"Tortilla de patatas"},
        {name:"Ratatouille"},
        {name:"Goat cheese salad"},
        {name:"Chili con carne"},
        {name:"Flamenkuche"},
        {name:"Poulet saute a l'oignon"},
        {name:"Pasta with mushrooms"},
        {name:"Mushroom risotto"},
        {name:"Salmon and cherry tomatoes"},
        {name:"Lentil soup"},
        {name:"Chicken and red cabbage"},
        {name:"Gratinated spinach pasta"},
        {name:"Quinoa salad"},
        {name:"Pasta with salmon"},
        {name:"Chicken curry"},
        {name:"French potatoes"},
        {name:"Paella"},
        {name:"Scrambled eggs"},
        {name:"Haloumi"},
        {name:"Tsatsiki"},
    ]
}
